68.tif.npy
110.tif.npy
290.tif.npy
411.tif.npy
511.tif.npy
584.tif.npy
850.tif.npy
857.tif.npy
1046.tif.npy
1075.tif.npy
1685.tif.npy
1706.tif.npy
1839.tif.npy
2005.tif.npy
2093.tif.npy
2315.tif.npy
2565.tif.npy
2607.tif.npy
3029.tif.npy
3142.tif.npy
3215.tif.npy
3259.tif.npy
3260.tif.npy
3481.tif.npy
3500.tif.npy
3894.tif.npy
3912.tif.npy
3971.tif.npy
3981.tif.npy
4301.tif.npy
4317.tif.npy
4360.tif.npy
4364.tif.npy
4404.tif.npy
4435.tif.npy
4682.tif.npy
4688.tif.npy
4699.tif.npy
4717.tif.npy
4830.tif.npy
4831.tif.npy
4833.tif.npy
5176.tif.npy
5323.tif.npy
5408.tif.npy
5418.tif.npy
5722.tif.npy
5748.tif.npy
5773.tif.npy
6012.tif.npy
6061.tif.npy
6065.tif.npy
6160.tif.npy
6551.tif.npy
6582.tif.npy
6592.tif.npy
6619.tif.npy
6817.tif.npy
7242.tif.npy
7259.tif.npy
7444.tif.npy
7452.tif.npy
7795.tif.npy
7958.tif.npy
8395.tif.npy
8461.tif.npy
8465.tif.npy
8484.tif.npy
8550.tif.npy
8610.tif.npy
8697.tif.npy
8776.tif.npy
8799.tif.npy
9199.tif.npy
9213.tif.npy
9216.tif.npy
9681.tif.npy
9765.tif.npy
9828.tif.npy
10073.tif.npy
10177.tif.npy
10354.tif.npy
10489.tif.npy
11042.tif.npy
11112.tif.npy
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 460, in load
    return pickle.load(fid, **pickle_kwargs)
ValueError: could not convert string to int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "merge_5_channels.py", line 66, in <module>
    main()
  File "merge_5_channels.py", line 51, in main
    image_file = np.load(target_path + "compound/" + files, allow_pickle=True)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/home/jovyan/mnt/external-images-pvc/ximeng/five_channel_images/compound/10826.tif' as a pickle
